src/mvc/CLIView.java, src/mvc/Controller.java, src/mvc/OptionsPanel.java, src/sorters/BogoSort.java, src/sorters/BubbleSort.java, src/sorters/CocktailSort.java, src/sorters/Sorter.java
=> Added option to sort in reverse (choose between ascending and descending)

src/sorters/BubbleSort.java, src/sorters/CocktailSort.java
=> Fixed sorting direction

src/mvc/Controller.java, src/sorters/BubbleSort.java, src/sorters/CocktailSort.java, src/sorters/SelectionSort.java, src/sorters/Sorter.java
=> Implemented selection sort and fixed minor bug

src/sorters/QuickSort.java, src/sorters/SelectionSort.java
=> Fixed stop button not working for certain algorithms

src/mvc/Controller.java, src/sorters/QuickSort.java, src/sorters/SelectionSort.java
=> Implemented quick sort and patched a few bugs

src/mvc/Controller.java, src/sorters/MergeSort.java
=> 6 merge sort

src/sorters/MergeSort.java
=> Fixed merge sort bug

src/mvc/GUIView.java
=> Improved sizing of panels in GUI

src/sorters/InsertionSort.java
implemented Insertion sort correspondind to the rest of the project.
=> InsertionSort.java

src/mvc/CLIView.java, src/mvc/Controller.java, src/mvc/OptionsPanel.java
CLI wouldn't sort in ascending order, bogo sort wouldn't shuffle.
Closes #35
=> Fixed bugs with CLI and with bogo sort

src/mvc/BarPanel.java, src/mvc/CLIView.java, src/mvc/Controller.java, src/mvc/OptionsPanel.java, src/mvc/Sound.java, src/sorters/BogoSort.java, src/sorters/BubbleSort.java, src/sorters/CocktailSort.java, src/sorters/InsertionSort.java, src/sorters/MergeSort.java, src/sorters/QuickSort.java, src/sorters/SelectionSort.java, src/sorters/Sorter.java
closes #32 
Is far from perfect and often has a lot of static but it works (sorta)!!
=> Added sounds

app/src/main/java/sortalgorithmvisualiser/mvc/GUIView.java, app/src/main/java/sortalgorithmvisualiser/mvc/OptionsPanel.java
Not perfect but good enough for now, dealing with JSwing and layout managers is too much of a pain to be worth it at the moment.
Closes #24
=> Improved options panel

app/src/main/java/sortalgorithmvisualiser/mvc/BarPanel.java, app/src/main/java/sortalgorithmvisualiser/mvc/Controller.java, app/src/main/java/sortalgorithmvisualiser/mvc/Model.java, app/src/main/java/sortalgorithmvisualiser/sorters/StalinSort.java
=> Implemented Stalin sort

app/src/main/java/sortalgorithmvisualiser/mvc/Controller.java, app/src/main/java/sortalgorithmvisualiser/mvc/GUIView.java, app/src/main/java/sortalgorithmvisualiser/mvc/Sound.java
=> Improved sound somewhat and fixed bug where speakers would sometimes peak

app/build.gradle.kts, app/src/main/java/sortalgorithmvisualiser/App.java, app/src/main/java/sortalgorithmvisualiser/mvc/BarPanel.java, app/src/main/java/sortalgorithmvisualiser/mvc/CLIView.java, app/src/main/java/sortalgorithmvisualiser/mvc/Controller.java, app/src/main/java/sortalgorithmvisualiser/mvc/GUIView.java, app/src/main/java/sortalgorithmvisualiser/mvc/OptionsPanel.java, app/src/main/java/sortalgorithmvisualiser/mvc/Sound.java, app/src/main/java/sortalgorithmvisualiser/sorters/BogoSort.java, app/src/main/java/sortalgorithmvisualiser/sorters/StalinSort.java, settings.gradle.kts
Added option to change speed of animation at the end, closes #37 
Fixed CLI crashing and not terminating properly, fixes #51 
Added sound to bogosort, closes #52 
Added support for command line arguments, and automatic skipping of prompt if either CLI or GUI is unavailable, closes #54
=> Stopped CLI crashing, added support for flags, added option for delay at end

app/src/main/java/sortalgorithmvisualiser/mvc/Controller.java, app/src/main/java/sortalgorithmvisualiser/mvc/OptionsPanel.java, app/src/main/java/sortalgorithmvisualiser/mvc/Sound.java
Also slightly improved sound, still not perfect though
=> Stopped user from shuffling mid-sort

.gitignore, README.md, app/build.gradle.kts, app/src/main/java/sortalgorithmvisualiser/mvc/Controller.java, app/src/main/java/sortalgorithmvisualiser/mvc/OptionsPanel.java, app/src/main/java/sortalgorithmvisualiser/mvc/Oscillator.java, app/src/main/java/sortalgorithmvisualiser/mvc/Sound.java, gradle/wrapper/gradle-wrapper.properties
Sound now uses a list of oscillators (very similar to how it was done [here](https://panthema.net/2013/sound-of-sorting/sound-of-sorting-0.6.5/src/SortSound.cpp.html)).
Also upgrades the Gradle version, and JDK to JDK 21.
Closes #61
=> Improved sound substantially

app/src/main/java/sortalgorithmvisualiser/mvc/Controller.java, app/src/main/java/sortalgorithmvisualiser/mvc/Model.java, app/src/main/java/sortalgorithmvisualiser/sorters/BogobogoSort.java
Implemented iteratively, rather than the recursive way described [here](https://www.dangermouse.net/esoteric/bogobogosort.html), but should result in the same process.
Closes #44
=> Implement bogobogo sort

app/build.gradle.kts, app/src/main/java/sortalgorithmvisualiser/mvc/Controller.java, app/src/main/java/sortalgorithmvisualiser/sorters/HeapSort.java
=> Implement heapsort

app/src/main/java/sortalgorithmvisualiser/mvc/BarPanel.java, app/src/main/java/sortalgorithmvisualiser/mvc/Controller.java, app/src/main/java/sortalgorithmvisualiser/mvc/Sound.java, app/src/main/java/sortalgorithmvisualiser/sorters/BogobogoSort.java, app/src/main/java/sortalgorithmvisualiser/sorters/BubbleSort.java, app/src/main/java/sortalgorithmvisualiser/sorters/CocktailSort.java, app/src/main/java/sortalgorithmvisualiser/sorters/HeapSort.java, app/src/main/java/sortalgorithmvisualiser/sorters/InsertionSort.java, app/src/main/java/sortalgorithmvisualiser/sorters/MergeSort.java, app/src/main/java/sortalgorithmvisualiser/sorters/QuickSort.java, app/src/main/java/sortalgorithmvisualiser/sorters/SelectionSort.java, app/src/main/java/sortalgorithmvisualiser/sorters/Sorter.java, app/src/main/java/sortalgorithmvisualiser/sorters/StalinSort.java
Bars being compared are now highlighted red.
Also, fix sound acting weirdly when the delay is short (~1ms or less).
Resolves #62
=> Colour bars that are being compared

app/src/main/java/sortalgorithmvisualiser/mvc/BarPanel.java, app/src/main/java/sortalgorithmvisualiser/mvc/Controller.java, app/src/main/java/sortalgorithmvisualiser/mvc/GUIView.java, app/src/main/java/sortalgorithmvisualiser/mvc/OptionsPanel.java
=> Add colour customisation settings

app/build.gradle.kts, app/src/main/java/module-info.java
=> Add way to build to standalone executable

app/src/main/java/sortalgorithmvisualiser/mvc/BarPanel.java, app/src/main/java/sortalgorithmvisualiser/mvc/Controller.java, app/src/main/java/sortalgorithmvisualiser/mvc/GUIView.java, app/src/main/java/sortalgorithmvisualiser/mvc/NormalisedScaler.java, app/src/main/java/sortalgorithmvisualiser/mvc/OptionsPanel.java, app/src/main/java/sortalgorithmvisualiser/mvc/Oscillator.java, app/src/main/java/sortalgorithmvisualiser/mvc/Sound.java, app/src/main/java/sortalgorithmvisualiser/sorters/BogoSort.java, app/src/main/java/sortalgorithmvisualiser/sorters/BogobogoSort.java, app/src/main/java/sortalgorithmvisualiser/sorters/BubbleSort.java, app/src/main/java/sortalgorithmvisualiser/sorters/CocktailSort.java, app/src/main/java/sortalgorithmvisualiser/sorters/HeapSort.java, app/src/main/java/sortalgorithmvisualiser/sorters/InsertionSort.java, app/src/main/java/sortalgorithmvisualiser/sorters/MergeSort.java, app/src/main/java/sortalgorithmvisualiser/sorters/QuickSort.java, app/src/main/java/sortalgorithmvisualiser/sorters/SelectionSort.java, app/src/main/java/sortalgorithmvisualiser/sorters/Sorter.java, app/src/main/java/sortalgorithmvisualiser/sorters/StalinSort.java
=> Add more customization settings to options panel

app/src/main/java/sortalgorithmvisualiser/mvc/BarPanel.java, app/src/main/java/sortalgorithmvisualiser/mvc/Controller.java, app/src/main/java/sortalgorithmvisualiser/mvc/GUIView.java, app/src/main/java/sortalgorithmvisualiser/mvc/OptionsPanel.java, app/src/main/java/sortalgorithmvisualiser/mvc/Sound.java
=> Redesign options panel

app/src/main/java/sortalgorithmvisualiser/mvc/BarPanel.java, app/src/main/java/sortalgorithmvisualiser/mvc/Controller.java, app/src/main/java/sortalgorithmvisualiser/mvc/GUIView.java, app/src/main/java/sortalgorithmvisualiser/mvc/Model.java, app/src/main/java/sortalgorithmvisualiser/mvc/OptionsPanel.java, app/src/main/java/sortalgorithmvisualiser/mvc/StatsPanel.java, app/src/main/java/sortalgorithmvisualiser/sorters/Sorter.java
=> Add stats menu with extra info

app/src/main/java/sortalgorithmvisualiser/mvc/BarPanel.java, app/src/main/java/sortalgorithmvisualiser/mvc/Controller.java, app/src/main/java/sortalgorithmvisualiser/mvc/GUIView.java, app/src/main/java/sortalgorithmvisualiser/mvc/Model.java, app/src/main/java/sortalgorithmvisualiser/mvc/OptionsPanel.java, app/src/main/java/sortalgorithmvisualiser/mvc/StatsPanel.java, app/src/main/java/sortalgorithmvisualiser/sorters/BitonicSort.java, app/src/main/java/sortalgorithmvisualiser/sorters/BogoSort.java, app/src/main/java/sortalgorithmvisualiser/sorters/BogobogoSort.java, app/src/main/java/sortalgorithmvisualiser/sorters/BubbleSort.java, app/src/main/java/sortalgorithmvisualiser/sorters/CocktailSort.java, app/src/main/java/sortalgorithmvisualiser/sorters/CombSort.java, app/src/main/java/sortalgorithmvisualiser/sorters/HeapSort.java, app/src/main/java/sortalgorithmvisualiser/sorters/InsertionSort.java, app/src/main/java/sortalgorithmvisualiser/sorters/MergeSort.java, app/src/main/java/sortalgorithmvisualiser/sorters/QuickSort.java, app/src/main/java/sortalgorithmvisualiser/sorters/SelectionSort.java, app/src/main/java/sortalgorithmvisualiser/sorters/Sorter.java, app/src/main/java/sortalgorithmvisualiser/sorters/StalinSort.java
=> Bitonic sort, comb sort, and bug fixes
